# Generated by Django 5.2.1 on 2026-09-16 12:18

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duration', models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))])),
                ('date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='Trophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('points', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(50)])),
                ('is_repeatable', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Trophy',
                'verbose_name_plural': 'Trophies',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro')], max_length=1)),
                ('experience_points', models.PositiveIntegerField(default=0)),
                ('level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SportActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.activity')),
                ('sport_type', models.CharField(choices=[('walk', 'Caminata'), ('run', 'Carrera'), ('weights', 'Pesas'), ('bike', 'Bicicleta'), ('pilates', 'Pilates'), ('yoga', 'Yoga'), ('hiit', 'HIIT')], max_length=20)),
                ('distance', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='La distancia no debe ser negativa')])),
                ('intensity', models.CharField(blank=True, choices=[('very_low', 'Muy baja'), ('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('very_high', 'Muy alta')], max_length=20, null=True)),
                ('sport_category', models.CharField(editable=False, max_length=20)),
            ],
            options={
                'verbose_name': 'Sport activity',
                'verbose_name_plural': 'Sport activities',
            },
            bases=('core.activity',),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject_category', models.CharField(choices=[('sciences', 'Ciencias'), ('socials', 'Sociales'), ('humanities', 'Humanidades'), ('languages', 'Idiomas'), ('programming', 'Programación'), ('other', 'Otro')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTrophy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obtained_at', models.DateTimeField()),
                ('trophy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trophy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_trophies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User trophy',
                'verbose_name_plural': 'User trophies',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='trophies',
            field=models.ManyToManyField(through='core.UserTrophy', to='core.trophy'),
        ),
        migrations.CreateModel(
            name='StudyActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.activity')),
                ('study_type', models.CharField(choices=[('theory', 'Teoría'), ('practice', 'Práctica'), ('other', 'Otro')], max_length=10)),
                ('concentration', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='La concentración debe ser mayor o igual a 0'), django.core.validators.MaxValueValidator(10, message='La concentración debe ser menor o igual a 10')])),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_activities', to='core.subject')),
            ],
            options={
                'verbose_name': 'Study activity',
                'verbose_name_plural': 'Study activities',
            },
            bases=('core.activity',),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_subject_per_user'),
        ),
    ]
