# Generated by Django 5.2.1 on 2026-08-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_subject_per_user'),
        ),
    ]
