# Generated by Django 5.2.1 on 2026-05-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trophy_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='sportactivity',
            options={'verbose_name': 'Sport activity', 'verbose_name_plural': 'Sport activities'},
        ),
        migrations.AlterModelOptions(
            name='studyactivity',
            options={'verbose_name': 'Study activity', 'verbose_name_plural': 'Study activities'},
        ),
        migrations.AlterModelOptions(
            name='trophy',
            options={'verbose_name': 'Trophy', 'verbose_name_plural': 'Trophies'},
        ),
        migrations.AlterModelOptions(
            name='usertrophy',
            options={'verbose_name': 'User trophy', 'verbose_name_plural': 'User trophies'},
        ),
    ]
