# Generated by Django 5.2.1 on 2026-05-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activity_options_alter_sportactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrophy',
            name='obtained_at',
            field=models.DateTimeField(),
        ),
    ]
