# Generated by Django 5.2.1 on 2026-08-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_activity_duration_alter_customuser_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportactivity',
            name='intensity',
            field=models.CharField(blank=True, choices=[('very_low', 'Muy baja'), ('low', 'Baja'), ('medium', 'Media'), ('high', 'Alta'), ('very_high', 'Muy alta')], max_length=20, null=True),
        ),
    ]
