# Generated by Django 5.2.1 on 2026-08-21 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sportactivity_intensity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportactivity',
            name='distance',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='La distancia no debe ser negativa')]),
        ),
        migrations.AlterField(
            model_name='studyactivity',
            name='concentration',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0, message='La concentración debe mayor o igual a 0'), django.core.validators.MaxValueValidator(10, message='La concentración debe ser menor o igual a 10')]),
        ),
    ]
